### ISSUE TITLE
Automate semester switching

### ISSUE THREAD

**Issue by Astra3** [SirValecekLuis/DiscordBot#13]
When switching semesters, there's a lot of category clicking and channel creating with "funny" descriptions. The bot should automate the following:

- Update categories:
  - Currently used semester categories:
    - [x] Add ` - archive` to their name
    - [x] Remove the entire class (e.g. Druhák) role from permissions
    - [x] Disallow Send Messages, Send Messages in Threads and Create Private/Public threads for everyone
    - [x] Reset View Channels for everyone to its default state
  - To be used semester categories:
    - [x] Remove ` - archive` from their name
    - [x] Add class permission to it and enable View Channels
    - [x] Disallow View Channels for everyone
    - [x] Allow Send Messages, Send Messages in Threads and Create Private/Public threads for everyone
  - It is important that no other modifications are made. Some categories (like first and second semester) do have additional permissions.
- [x] Reorder the now old semesters below voice channels and the active semesters above, all in descending order
- [ ] (optional) Accept a "list" of channels, their descriptions and category name to create these channels in.
- [ ] (optional) Add the next study year role to members missing them (i.e. add role "Druhák" to members having only "Prvák" when switching to next year) -- it seems like a good idea on paper but we might wanna ask others about this

The execution of this functionality (through a slash command for example) **should not** be taken lightly. The bot should ask for confirmation (i.e. through the use of buttons) with **clear** description for what the command is and it should also check, if the person calling the command has the "Administrator" permission.

To help develop this task, you can create a template from the existing server to use for testing. This feature should also be ready for eventual addition of 5th, 6th and even future semesters. This feature should also be flexible, as requirements may and do change frequently.

**Comment by SirValecekLuis** [comment]
We shall not forget in the future to add role ids from our main server before switching.
