### ISSUE TITLE
Bugs and problems in `automate-semester-switching`

### ISSUE THREAD

**Issue by ivoslovacek** [SirValecekLuis/DiscordBot#22]
I will try to find some bugs, problems and recommendations for the implemented features requested in #13 

As of [`06427bc`](https://github.com/SirValecekLuis/DiscordBot/commit/06427bc5a784e2cc2deccebd2431587cc8e85882), I have found these things so far:

- [x] hard coded role names in [`semester_switching.py`](https://github.com/SirValecekLuis/DiscordBot/blob/06427bc5a784e2cc2deccebd2431587cc8e85882/bot/semester_switching.py#L8)

```python
# Fix: This should not be hard coded, but instead it should be stored in db.
ROLES = {1: "1️⃣ Prvák", 2: "2️⃣ Druhák", 3: "3️⃣ Třeťák", 4: "4️⃣ Čtvrťák", 5: "5️⃣ Páťák"}
```

Also I suggest that we don't use role names at all. We should always prefer to use role IDs.

- [x] invalid concatenating of strings with exceptions in [`semester_switching.py`](https://github.com/SirValecekLuis/DiscordBot/blob/06427bc5a784e2cc2deccebd2431587cc8e85882/bot/semester_switching.py#L115-L117)

```python
except Exception as e:
    text = " | ".join([category.name for category in visited_categories])
    # Fix: you can't concatenate strings with exceptions (maybe try to cast the exception to string?)
    raise Exception("Something failed. processed categories attached + error" + text + e)
```

**Comment by SirValecekLuis** [comment]
I will keep this open and if you find any bug or if you want to recommend something, please, make a new comment under this one.
