### ISSUE TITLE
Branch auto_voice: make it use the database

### ISSUE THREAD

**Issue by ivoslovacek** [SirValecekLuis/DiscordBot#3]
Automatic voice channel IDs and all channel IDs created by 'auto_voice.py' should be stored in a database instead of being stored solely in local variables.

**Comment by SirValecekLuis** [comment]
There is no reason to put it in a database, to be honest. It would be an issue only if the bot crashed during the channel being opened, which we can fix easily by removing the channel manually. I would keep it without the database for now. If it seems like an issue in the future we can implement it (the chance of the bot being dropped while VC will be opened is very low to zero)

**Comment by ivoslovacek** [comment]
I guess, there is also the issues of having to manually set up the channel ID of the automatic voice channel every time the bot starts up. It would still be better to integrate at least this part to the database, because doing it everytime we pull newest changes will be tedious. It would be fine to have the ability to also set the channel ID to a session variable, which would be used with a higher priority than the database one, for testing purposes.

**Comment by ivoslovacek** [comment]
This should improve the way channels are deleted along side with other improvements . There are also preperations for using auto voice master (the channel that should be joined if you want to have a new vc created ) ID from the database
