### ISSUE TITLE
Add logging or any warning system when issue occurs

### ISSUE THREAD

**Issue by SirValecekLuis** [SirValecekLuis/DiscordBot#6]
Logging or any type of system that should warn us in DMs or specified DC channels if any error happens in the code so we can react to it with detailed information on where and what failed in the code.

**Comment by Astra3** [comment]
It seems stupid to log this into a discord channel, this should be logged by using the `logging` module. Pycord implements its logging messages through it and it only seems sensible to extend their logger with custom messages, if needed, and log them on the server.

**Comment by SirValecekLuis** [comment]
So far I have implemented a function which will respond to the user when an unexpected error occurs and sends info to the bot-development channel so we are informed of what exactly happened in the code and what is the error message.

So far event error handling is not solved, just for slash commands. Bear In mind you have to add the on_command_error in each cog.

**Comment by SirValecekLuis** [comment]
So far this issue will be solved by printing info into a console terminal and then viewing the console terminal when we migrate to VPS for any errors. If that's gonna happen I'll close this idea as it will not be needed.

**Comment by SirValecekLuis** [comment]
Solved with console logging and can be viewed (I have access to logs).
